var pousseeinit = 1.2;
var poussee = pousseeinit;
poussee_arriere = 0.5;
inertieinit = 0.91;
inertie = inertieinit;
rotation = 2;
maxSpeed = 10;
hit = false;
bighit = false;
var c = 0;
var l = 0;
var r = 0;
var v = 0;
var k = 0;
var x = 0;
var o = 0;
var w = 0;
var y = 0;
t0 = getTimer();
double = ["00","01","02","03","04","05","06","07","08","09"];
_root.voiture.pot._visible = 0;
right = false;
left = false;
score = 0;
addScore = function(points)
{
   score += points;
   score_txt.text = score;
};
_root.batimentExplose = false;
var introZic = new Sound();
introZic.attachSound("loop");
introZic.start(0,99);
var explosition = new Sound();
explosition.attachSound("boom");
var vache = new Sound();
vache.attachSound("vache");
var mouton = new Sound();
mouton.attachSound("mouton");
_quality = "MEDIUM";
